language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

script:
- travis_retry xcodebuild -workspace MMCache.xcworkspace -scheme "MMCache" -destination "platform=iOS Simulator,name=iPhone 7" build-for-testing test | xcpretty
